ACHIV_FILTER_MISSION_LIST = {
	{
		{'ACH_TROLL','ACH_RADIO', 'ACH_CYRUS', 'ACH_ASPEED_1'},
		{'ACH_CARGO', 'ACH_JERRY', 'ACH_TIGER', 'ACH_ASPEED_2'},
		{'ACH_FAUST', 'ACH_POKR', 'ACH_NOSCI', 'ACH_ASPEED_3'},
		{'ACH_GUN', 'ACH_BASE', 'ACH_INFANTRY', 'ACH_ASPEED_4'},
		{'ACH_TAME', 'ACH_RADAR', 'ACH_APEKILLER', 'ACH_ASPEED_5'},
		{'ACH_BASEDESTROYER', 'ACH_SURV', 'ACH_FULLCARGO', 'ACH_ASPEED_6'},
		{'ACH_COMMANDO', 'ACH_TANKACE', 'ACH_HITMAN', 'ACH_ASPEED_7'},
		{'ACH_HEAVYGUN', 'ACH_BLITZKRIEG', 'ACH_ARMOR', 'ACH_ASPEED_8'},
		{'ACH_BULLDOZER', 'ACH_COUNTERSTRIKE', 'ACH_SIBMINE', 'ACH_ASPEED_9'},
		{'ACH_POWER', 'ACH_SNIPER', 'ACH_ARCH', 'ACH_ASPEED_10'},
		{'ACH_ARABTECH', 'ACH_FRIEND', 'ACH_EAST', 'ACH_GENERAL', 'ACH_ASPEED_11'},
		{'ACH_PATH', 'ACH_LASER', 'ACH_ROCKET', 'ACH_ASPEED_12'},
		{'ACH_MASHA', 'ACH_REMOTE', 'ACH_DEFMASTER', 'ACH_ASPEED_13'},
		{'ACH_DOUBLE', 'ACH_APE', 'ACH_FORT', 'ACH_ASPEED_14'},
		{'ACH_POWELL', 'ACH_ALLIANCE', 'ACH_SIBROCKET', 'ACH_ASPEED_15'},
		{'ACH_EYE', 'ACH_ALARM', 'ACH_NOINVIS', 'ACH_TEAM', 'ACH_ASPEED_16'},
		{'ACH_COMRADE', 'ACH_HACK','ACH_ASPEED_17'},
		{'ACH_PACIFIST', 'ACH_DIPLOMACY', 'ACH_ONEMANARMY', 'ACH_ASPEED_18'},
		{'ACH_ARTIFACT', 'ACH_OMAR', 'ACH_ECONOMY', 'ACH_ASPEED_19'},
		{}
	}
};